on:
  workflow_call:

jobs:
  calculate-vars:
    runs-on: ubuntu-latest

    outputs:
      vars: ${{ steps.vars.outputs.vars }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Variables
        id: vars
        run: |
          tag_name=${GITHUB_REF#refs/*/}
          package_name=${GITHUB_REPOSITORY#*/}
          message_text=${{ github.event.head_commit.message }}
          vars=$(
            echo "{ \"tag_name\": \"$tag_name\", \"package_name\": \"$package_name\", \"message_text\": \"$message_text\" }"
          )
          echo "----------------------"
          echo $vars
          echo "----------------------"
          echo "vars=$vars" >> $GITHUB_OUTPUT

  check-prerequisites:
    needs: calculate-vars
    runs-on: ubuntu-latest
    name: Check about the prerequisites

    env:
      vars: ${{ fromJson(needs.calculate-vars.outputs.vars) }}
      TAG_NAME_PATTERN: ^v[0-9]+\.[0-9]+\.[0-9]+$
      COMMIT_MESSAGE_PATTERN: ^Release[[:space:]]v[0-9]+\.[0-9]+\.[0-9]+$
      PACKAGE_VERSION_PATTERN: "Release ${{ env.vars.tag_name }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Package version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1

      - name: Check Tag Name
        run: |
          if [[ ! ${{ env.vars.tag_name }} =~ ${{ env.TAG_NAME_PATTERN }} ]]
          then
            echo "Tag does not follow following convention ${{ env.TAG_NAME_PATTERN }}!!!"
            exit 1
          fi

      - name: Check Commit Message
        run: |
          if [[ ! ${{ env.vars.message_text }} =~ ${{ env.COMMIT_MESSAGE_PATTERN }} ]]
          then
            echo "Publish failed: Commit message not conform (Release v[0-9]+\.[0-9]+\.[0-9]+)!!!"
            exit 1
          fi

      - name: Check Commit Version
        run: |
          if [[ ! "${{ env.vars.message_text }}" == "${{ env.PACKAGE_VERION_PATTERN }}" ]]
          then
              echo "Publish failed: Commit version not match!!!"
              echo "Tag: ${{ env.vars.tag_name }} Message: ${{ env.vars.message_text }}"
              exit 1

          fi

      - name: Check Package Version
        run: |
          if [[ ! "v${{ steps.extract_version.outputs.version }}" == "${{ env.vars.tag_name }}" ]]
          then
              echo "Publish failed: Package version not match!!!"
              echo "Package version: ${{ steps.extract_version.outputs.version }} Tag version: ${{ env.vars.tag_text }}"
              exit 1
          fi

  build-n-publish:
    needs: check-prerequisites
    runs-on: ubuntu-latest
    name: Publish the Package
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Publish on NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
